server:
  port: 8080

debug: true


spring:
  devtools:
    restart:
      enabled: true
data:
  source:
    properties:
      scheme: "http"
      host: "localhost"
      port: "7200"
      repository-id: "cvi"
      initial-load-file-location: "cvi-vocabulary.sparql"
    endpoints:
      create-repository: "/rest/repositories"
      delete-repository: "/rest/repositories/cvi"
      read-all-repository: "/repositories"
      update-repository-statements: "/repositories/cvi/statements"
      query-repository-statements: "/repositories/cvi"


logging:
  level:
    org:
      springframework:
        security: "DEBUG"
        web: "DEBUG"
---

debug: true

spring:
  profiles: dev

data:
  source:
    properties:
      scheme: "http"
      host: "localhost"
      port: "7210"
      repository-id: "cvi"
      initial-load-file-location: "cvi-vocabulary.sparql"
    endpoints:
      create-repository: "/rest/repositories"
      delete-repository: "/rest/repositories/cvi"
      read-all-repository: "/repositories"
      update-repository-statements: "/repositories/cvi/statements"
      query-repository-statements: "/repositories/cvi"
logging:
  level:
    org:
      springframework:
        security: "DEBUG"
        web: "DEBUG"
---

spring:
  profiles: docker
  devtools:
    restart:
      enabled: false

data:
  source:
    properties:
      scheme: "http"
      host: "cvi"
      port: "7200"
      repository-id: "cvi"
      initial-load-file-location: "cvi-vocabulary.sparql"
    endpoints:
      create-repository: "/rest/repositories"
      delete-repository: "/rest/repositories/cvi"
      read-all-repository: "/repositories"
      update-repository-statements: "/repositories/cvi/statements"
      query-repository-statements: "/repositories/cvi"

debug: false
