server:
  port: 8090

debug: true


spring:
  devtools:
    restart:
      enabled: true
data:
  source:
    properties:
      scheme: "http"
      host: "localhost"
      port: "7200"
      repository-id: "cvi"
      initial-load-file-location: "cvi-vocabulary.sparql"
    endpoints:
      create-repository: "/rest/repositories"
      delete-repository: "/rest/repositories/cvi"
      read-all-repository: "/repositories"
      update-repository-statements: "/repositories/cvi/statements"
      query-repository-statements: "/repositories/cvi"

error:
  message:
    hardware-type:
      form-control:
        hardware-component: "Hardware component is required"
        category: "Category is required"
        label: "Label is required"
        comment: "Comment is required"

logging:
  level:
    org:
      springframework:
        security: "DEBUG"
        web: "DEBUG"
---


spring:
  profiles: dev

server:
  port: 8090

debug: true

data:
  source:
    properties:
      scheme: "http"
      host: "localhost"
      port: "7210"
      repository-id: "cvi"
      initial-load-file-location: "cvi-vocabulary.sparql"
    endpoints:
      create-repository: "/rest/repositories"
      delete-repository: "/rest/repositories/cvi"
      read-all-repository: "/repositories"
      update-repository-statements: "/repositories/cvi/statements"
      query-repository-statements: "/repositories/cvi"
logging:
  level:
    org:
      springframework:
        security: "DEBUG"
        web: "DEBUG"

error:
  message:
    hardware-type:
      form-control:
        hardware-component: "Hardware component is required"
        category: "Category is required"
        label: "Label is required"
        comment: "Comment is required"
---

spring:
  profiles: docker
  devtools:
    restart:
      enabled: false

data:
  source:
    properties:
      scheme: "http"
      host: "cvi"
      port: "7200"
      repository-id: "cvi"
      initial-load-file-location: "cvi-vocabulary.sparql"
    endpoints:
      create-repository: "/rest/repositories"
      delete-repository: "/rest/repositories/cvi"
      read-all-repository: "/repositories"
      update-repository-statements: "/repositories/cvi/statements"
      query-repository-statements: "/repositories/cvi"

debug: false

server:
  port: 8080

error:
  message:
    hardware-type:
      form-control:
        hardware-component: "Hardware component is required"
        category: "Category is required"
        label: "Label is required"
        comment: "Comment is required"