version: "3"
services:
  db-1:
    container_name: users
    image: graph-db-free
    ports:
      - "7205:7200"
  app-users-management:
    container_name: app.users
    image: users-management
    ports:
      - "8005:8080"
    depends_on:
      - db-1
  db-2:
    container_name: cvi
    image: graph-db-free
    ports:
      - "7210:7200"
  app-entities-management:
    container_name: app.entities
    image: entities-management
    ports:
      - "8010:8080"
    depends_on:
      - db-2
  cvi-web:
    container_name: web.cvi
    image: cvi-web
    ports:
      - "80:80"
    depends_on:
      - app-users-management
      - app-entities-management